### ISSUE TITLE
Kenapa saya dah upload tapi tak masih tak ada dalm senarai plugin

### ISSUE THREAD

**Issue by dinware10** [wzul/Billplz-for-Prestashop#1]
![image](https://cloud.githubusercontent.com/assets/9082927/17649093/e1c1e06a-625d-11e6-869c-46c75c04b304.png)

**Comment by wzul** [comment]
Cuba try upload secara manual ke installation directory / modules

**Comment by dinware10** [comment]
ok say  akan cuba

**Comment by wzul** [comment]
klu x boleh juga, pm facebook page. fb.com/billplzplugin . saya akan assist utk installation

**Comment by dinware10** [comment]
Saya dah buat tetapi dalam system modul masih tak ada
[image: Inline image 1]

**Comment by wzul** [comment]
Saya telah test dan pastikan solution untuk masalah diatas.
1. Muat turun file: https://codeload.github.com/wzul/Billplz-for-Prestashop/zip/master
2. Rename nama fail tersebut kepada billplz.zip
3. Rename nama folder dalam fail arkib (billplz.zip) daripada "Billplz-for-Prestashop-master" kepada "billplz"
4. Upload dan Install.
5. Selesai

Sila rujuk 2 gambar dibawah untuk rujukan. 

https://postimg.org/image/jzg6lywo9/
https://postimg.org/image/8bm4rf7jd/

**Comment by dinware10** [comment]
OK sudah boleh terima kasih :-)

2016-08-15 7:25 GMT+08:00 Din Ware dinware10@gmail.com:

**Comment by wzul** [comment]
sama-sama :)
